// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wordBreakD
vector<string> wordBreakD(string str, vector<string> MyDictionary);
RcppExport SEXP _uglypaRse_wordBreakD(SEXP strSEXP, SEXP MyDictionarySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type str(strSEXP);
    Rcpp::traits::input_parameter< vector<string> >::type MyDictionary(MyDictionarySEXP);
    rcpp_result_gen = Rcpp::wrap(wordBreakD(str, MyDictionary));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uglypaRse_wordBreakD", (DL_FUNC) &_uglypaRse_wordBreakD, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_uglypaRse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
